---
kind: pipeline
type: docker
name: default

steps:
  - name: install-deps
    image: cypress/included:3.8.1
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    commands:
      - yarn install

  - name: test
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    image: cypress/included:3.8.1
    commands:
      - yarn run test

volumes:
  - name: yarn
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-yarn

  - name: cache
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-cache
