---
kind: pipeline
type: docker
name: default

steps:
  - name: install-deps
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn install

  - name: test
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run test

  - name: lint
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run lint


volumes:
  - name: cache
    host:
      path: /tmp/cache
