---
kind: pipeline
type: docker
name: default

steps:
  - name: install-deps
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn install

  - name: test
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run test

volumes:
  - name: cypress-cache
    host:
      path: /tmp/cypress-cache

