---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run test
      - yarn run lint
  - name: lint
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run lint
