---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install-deps
    image: cypress/included:3.8.1
    volumes:
      - name: yarn
        path: /root/.cache/yarn/v6
    commands:
      - yarn install
      - ls ~/.cache -la
      - yarn cache dir
      - ls /root/.cache/yarn/v6

  - name: test
    volumes:
      - name: yarn
        path: /root/.cache/yarn/v6
    image: cypress/included:3.8.1
    commands:
      - yarn run test

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: yarn
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-yarn

  - name: cache
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-cache
