---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-node-modules-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: node-modules
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install-node-modules
    image: cypress/included:3.8.1
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    depends_on:
      - restore-node-modules-cache
    commands:
      - yarn install

  - name: lint
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    image: cypress/included:3.8.1
    depends_on:
      - build
    commands:
      - yarn run lint

  - name: build
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    image: cypress/included:3.8.1
    depends_on:
      - install-node-modules
    commands:
      - yarn run build:test

  - name: test
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    image: cypress/included:3.8.1
    failure: ignore
    depends_on:
      - build
    commands:
      - yarn run test:cypress:run

  - name: coverage
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn/v4
    image: cypress/included:3.8.1
    depends_on:
      - test
    commands:
      - yarn run test:coverage

  - name: save-node-modules-cache
    image: drillster/drone-volume-cache
    depends_on:
      - coverage
      - test
      - lint
    volumes:
      - name: node-modules
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: yarn
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-yarn

  - name: node-modules
    host:
      path: /tmp/vue-webpack-typescript-drone-v1-cache

trigger:
  event:
    exclude:
      - pull_request
