---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-node-modules-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./yarn-cache

  - name: install-node-modules
    image: cypress/included:3.8.1
    depends_on:
      - restore-node-modules-cache
    commands:
      - ls ./ -lad
      - yarn config set cache-folder /root/yarn-cache
      - yarn config get cache-folder
      - ls -la /usr/local/share/.cache/yarn/v4
      - yarn install
      - ls -la /usr/local/share/.cache/yarn/v4

  - name: save-node-modules-cache
    image: drillster/drone-volume-cache
    depends_on:
      - install-node-modules
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./yarn-cache
        - ./node_modules

  - name: build
    image: cypress/included:3.8.1
    depends_on:
      - install-node-modules
    commands:
      - yarn run build:test

  - name: lint
    image: cypress/included:3.8.1
    depends_on:
      - build
    commands:
      - yarn run lint

  - name: test
    image: cypress/included:3.8.1
    failure: ignore
    depends_on:
      - build
    commands:
      - yarn run test:cypress:run

  - name: coverage
    image: cypress/included:3.8.1
    depends_on:
      - test
    commands:
      - yarn run test:coverage

volumes:
  - name: cache
    host:
      path: /var/lib/cache

trigger:
  event:
    exclude:
      - pull_request
