---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ~/.cache/Cypress

  - name: install-deps
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn install

  - name: test
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run test

  - name: lint
    image: mhart/alpine-node:13.6.0
    commands:
      - yarn run lint

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ~/.cache/Cypress


volumes:
  - name: cache
    host:
      path: /tmp/cache
