language: node_js
node_js:
  - "node"
script:
  - nvm install
  - nvm use
  - yarn run test
  - yarn run test:codecov
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache
    - ~/.nvm
