# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node environment specified in .nvmrc
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15.0.1'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: install npm dependencies
        run: yarn config set cache-folder `pwd`/yarn-cache && yarn install --frozen-lockfile
      - name: build
        run: yarn run build:test:no-progress
      - name: test-cypress
        run: yarn run test:cypress:run:report
      - name: test-unit
        run: yarn run test:unit
      - name: coverage
        run: yarn run test:coverage
      - name: eslint
        run: yarn run lint
