name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node environment specified in .nvmrc
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15.0.1'
      # Restores cache, so every time yarn install didn't do the same thing
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: install npm dependencies
        run: yarn config set cache-folder `pwd`/yarn-cache && yarn install --frozen-lockfile
  build:
    needs: [install-deps]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: yarn run build:test
  lint:
    needs: [install-deps]
    runs-on: ubuntu-latest
    steps:
      - name: eslint
        run: yarn run lint
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: yarn run test:cypress:run:report
  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: coverage
        run: yarn run test:coverage
      - name: eslint
        run: yarn run lint
